# The URL the site will be built for
base_url = "https://0xferrous.github.io"
title = "0xferrous - Development Blog"
description = "Personal development blog covering programming, tools, and technical insights."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{name = "tags"}]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "0xferrous"
keywords = ["development", "programming", "coding", "tools", "tech", "software"]
og_image = "/images/og-image.png"
twitter_username = "0xferrous"
theme = "auto"
stylesheets = [
    "recursive-font.css"
]
socials = [
    { name = "github", url = "https://github.com/0xferrous", icon = "github" },
    { name = "twitter", url = "https://twitter.com/0xferrous", icon = "twitter" },
]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/tags", url = "/tags", weight = 3 },
]
